# This file is used to build the development container.
# For more information, see: https://containers.dev/guide/dockerfile
FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm

# You can add custom OS packages here, if needed.
# For example:
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
